apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vault-serviceaccount
  labels:
    app: kube-vault
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-vault-role
  labels:
    app: kube-vault
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-vault-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: kube-vault-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-vault-role
  apiGroup: rbac.authorization.k8s.io