name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Build
      env: 
        GO111MODULE: on
      run: |
        go mod download
        go build -o ./bin/main
